name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write credentials.json
      run: echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json

    - name: Write token.json
      run: echo "${{ secrets.TOKEN_JSON }}" > token.json

    - name: Write .env file
      run: echo "${{ secrets.DOTENV }}" > .env

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ai-assistant-raja904
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

    
